apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secure-payment

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: secure-payment-platform
  app.kubernetes.io/managed-by: kustomize
