apiVersion: v1
kind: Namespace
metadata:
  name: secure-payment
  labels:
    app.kubernetes.io/part-of: secure-payment-platform
    # Label for Kyverno policy targeting
    security.supply-chain/enforced: "true"
